pipeline {
    
    agent any 
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                WithSonarQubeEnv('SonarQube2.11') {
                    sh 'mvn clean package sonar:sonar'
                }
            }
        } 
    }
}
