pipeline {
    
    environment {
    registry = "https://hub.docker.com/repository/docker/snehalshirsath/devops_repo"
    dockerImage = ""
  }
    
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                WithSonarQubeEnv('SonarQube2.11') {
                    sh 'mvn clean package sonar:sonar'
                }
            }
        }
        
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        
    }
}
