pipeline{
    agent { label 'kubepod' } //pod template label
    
    stages{
        stage('fetch'){
            steps{
                git branch: 'master', url: 'https://github.com/snehalshirsath/jenkins-data.git'
            }
        }
        stage('deploy'){
            steps{
               dir("jenkins-eks-connection"){
               //kubernetesDeploy(configs: "machineinfo-deployment.yaml", kubeconfigId: "final-kubeconfig")
               sh 'kubectl apply -f machineinfo-deployment.yaml -n jenkins'
            }
			}
        }
    }
}
